### ISSUE TITLE
All builds failing, something about unable to resolve package reference

### ISSUE THREAD

**Issue by odrobnik** [SwiftPackageIndex/SwiftPackageIndex-Server#725]
What is going on here, why are all builds of Kvitto red? 

https://swiftpackageindex.com/Cocoanetics/Kvitto/builds

**Comment by Sherlouk** [comment]
If you look further down the error log you'll find this information which is more helpful:
```
  found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Core/Info.plist

  found 3 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Test/Resources/receipt
    /Test/Resources/sandboxReceipt
    /Test/Info.plist
```

Essentially this is just saying that, in your Package.swift you need to explicitly tell Swift Package Manager what to do with non-source files (such as plists or resources). I suspect you want the `Resources/` directory to be marked as resources so you can use them, but the Info.plists are likely unnecessary.

Some more documentation can be found here: https://developer.apple.com/documentation/swift_packages/bundling_resources_with_a_swift_package

**Comment by odrobnik** [comment]
That is wrong. DTFoundation has `// swift-tools-version:5.2` which means it doesn't support resources yet.

If you run `swift package describe` locally you see that that respects the version at the top. 

Only if I change that to `5.3` then swift will insist on me excluding unknown files or declaring them as resources.

**Comment by daveverwer** [comment]
Hi Oliver, and thanks for reporting this. I'm sure we can it sorted out.

I've just had a quick look at this and I think I can see what's going on. It looks to be related to the beta 4 version of Xcode that we used to compile Kvitto with. You can see the Xcode version that we used in the [build command on the logs page](https://swiftpackageindex.com/builds/AE0F3C2C-8AE7-408A-8804-EF84B745E287).

So if I run your build with Xcode 12 beta 4, I get two errors:

```
$ env DEVELOPER_DIR="/Applications/Xcode_12_beta_4.app" xcrun swift build
error: found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/dave/Desktop/Kvitto/Core/Info.plist

error: found 3 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/dave/Desktop/Kvitto/Test/Resources/receipt
    /Users/dave/Desktop/Kvitto/Test/Resources/sandboxReceipt
    /Users/dave/Desktop/Kvitto/Test/Info.plist
```

I get the same errors if I run `swift package describe`

```
$ env DEVELOPER_DIR="/Applications/Xcode_12_beta_4.app" xcrun swift package describe
error: found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/dave/Desktop/Kvitto/Core/Info.plist

error: found 3 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/dave/Desktop/Kvitto/Test/Info.plist
    /Users/dave/Desktop/Kvitto/Test/Resources/receipt
    /Users/dave/Desktop/Kvitto/Test/Resources/sandboxReceipt

Name: Kvitto
Path: /Users/dave/Desktop/Kvitto
Modules:
    Name: KvittoTests
    C99name: KvittoTests
    Type: test
    Module type: SwiftTarget
    Path: /Users/dave/Desktop/Kvitto/Test
    Sources: Source/KvittoTests.swift

    Name: Kvitto
    C99name: Kvitto
    Type: library
    Module type: SwiftTarget
    Path: /Users/dave/Desktop/Kvitto/Core
    Sources: Source/Functions.swift, Source/InAppPurchaseReceipt.swift, Source/PKCS7Container.swift, Source/Receipt.swift
```

If I run the same commands with Xcode 12 GM/Final then those errors become warnings:

```
$ env DEVELOPER_DIR="/Applications/Xcode_12.app" xcrun swift build           
warning: found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/dave/Desktop/Kvitto/Core/Info.plist

warning: found 3 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/dave/Desktop/Kvitto/Test/Resources/receipt
    /Users/dave/Desktop/Kvitto/Test/Info.plist
    /Users/dave/Desktop/Kvitto/Test/Resources/sandboxReceipt
```

and 

```
$ env DEVELOPER_DIR="/Applications/Xcode_12.app" xcrun swift package describe       
warning: found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/dave/Desktop/Kvitto/Core/Info.plist

warning: found 3 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
    /Users/dave/Desktop/Kvitto/Test/Resources/receipt
    /Users/dave/Desktop/Kvitto/Test/Resources/sandboxReceipt
    /Users/dave/Desktop/Kvitto/Test/Info.plist

Name: Kvitto
Path: /Users/dave/Desktop/Kvitto
Modules:
    Name: KvittoTests
    C99name: KvittoTests
    Type: test
    Module type: SwiftTarget
    Path: /Users/dave/Desktop/Kvitto/Test
    Sources: Source/KvittoTests.swift

    Name: Kvitto
    C99name: Kvitto
    Type: library
    Module type: SwiftTarget
    Path: /Users/dave/Desktop/Kvitto/Core
    Sources: Source/Functions.swift, Source/InAppPurchaseReceipt.swift, Source/PKCS7Container.swift, Source/Receipt.swift
```

We know it's not ideal that our 5.3 builds are still showing results from beta versions of Xcode, but we're waiting until [#679](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/679#issuecomment-697342354) is resolved before we wipe out the beta build results as it's a significant amount of processing to build everything again and we only really want to do it once.

Please do also bear with us, we know what we have built here isn't perfect. We are doing the best we can to get accurate results though.

**Comment by daveverwer** [comment]
In short, you shouldn't have to do anything for this to eventually be fixed. We will wipe the build results for 5.3 as #679 is resolved, and your red crosses should turn green for Swift 5.3.

**Comment by odrobnik** [comment]
Well, I still want to update DTFoundation's package definition to the 5.3 format, then I guess those errors would go away. Would it re-build after that again? If I re-tag the same versions? Or only if I tag a new version?

**Comment by odrobnik** [comment]
@daveverwer I've updated and re-tagged both Kvitto and DTFoundation to work with the Swift 5.3 PM - so that `swift package describe` doesn't complain any more about those extra files. Is there a way to trigger the builds for those again?

**Comment by daveverwer** [comment]
No need to do anything, as soon as the server sees the new commit on `develop` and the new tag it'll rebuild. It should be at most a couple of hours until you see new results.

**Comment by daveverwer** [comment]
Actually it looks like they're already in the queue, the ARM builds and Linux builds already finished.

<img width="576" alt="Screenshot 2020-09-29 at 15 52 55@2x" src="https://user-images.githubusercontent.com/5180/94575229-eca62600-026b-11eb-95aa-073aad43da7e.png">

**Comment by odrobnik** [comment]
For Linux it says that the tools on the server are 4.something - there‘s no way how I could make that test build go green, right?

**Comment by odrobnik** [comment]
Could you trigger the builds for Kvitto and DTFoundation again? I fixed some things and deleted the tag and re-added it, but it does not seem to schedule new builds. Rather I see a lot of failures from the 1.7.15 tag not being found on DTFoundation.

**Comment by finestructure** [comment]
I’m seeing

```
In file included from In file included from /host/.build/checkouts/DTFoundation/Core/Source/iOS/UIView+DTFoundation.m:9:
/host/.build/checkouts/DTFoundation/Core/Source/iOS/UIView+DTFoundation.h:11:9: fatal error: 'Availability.h' file not found
```

here: https://swiftpackageindex.com/builds/88385661-BFAB-43E6-B922-502F5652AD8B

We detect changes in tag and on the default branch regularly, including tag moves. I.e. it’ll automatically rebuild but it can take a couple of hours, depending on system load and timing.

**Comment by finestructure** [comment]
BTW, that build details page also shows the exact build command, so if you want to “pre-flight” test it, you could run that locally. Especially with docker that’s actually quite a bit simpler and more reliable than installing the exact Xcode version or using a different one.

**Comment by odrobnik** [comment]
Yeah, buy why is it even trying to build that? It is not a supported platform according to the package file.

**Comment by finestructure** [comment]
The platforms clause is not an exclusive list of supported platforms. It’s a list of platform minimum versions, if set. Absence of a platform just means there’s no version constraint whatsoever.

**Comment by odrobnik** [comment]
Ok, about the "pre-flight" testing.... I have tried that, but it references a scheme. For example, for DTFoundation it references a DTFoundation scheme.... where does that come from? (My schemes building a framework and not Swift package are named differently) Do you generate an xcodeproj and scheme from the package? 

Do you have documentation somewhere that would allow me to execute the various builds on my computer?

**Comment by daveverwer** [comment]
Documentation on how we build the packages, and about the scheme we use is here: https://swiftpackageindex.com/docs/builds#built-how

**Comment by finestructure** [comment]
I belive this is fixed now - please reopen if there are lingering issues!

**Comment by odrobnik** [comment]
@finestructure Question: Why does this fail? Does the build with Xcode require that there is an OSX scheme with the exact name as the package? 

https://swiftpackageindex.com/builds/DD754B81-DF80-498E-9CCE-6D5EB8E9C951

**Comment by finestructure** [comment]
Hi @odrobnik , not quite, it's a little more complex than that. We've documented how we pick the scheme in the "How are packages built?" section that Dave linked to above: https://swiftpackageindex.com/docs/builds#built-how

**Comment by odrobnik** [comment]
So @finestructure, this just says that you are generating the Xcode project with SPM, right?

(which BTW - according to the Swift guys - is a legacy tool as it doesn't support resources.)

**Comment by finestructure** [comment]
If by that you mean `swift generate-xcodeproj` - no, we're not doing that. If we don't find a suitable scheme we remove all xcodeproj and xcworkspace files and let SPM auto discover the scheme.

**Comment by odrobnik** [comment]
How can that work? Don't Schemes reference workspaces... if you remove those how can anything be built? Where can I see the actual commands being executed?

**Comment by finestructure** [comment]
It autogenerates an internal scheme - have a look at the build command we show on the build details page and run it after deleting the project files. You'll see what it does then, that's exactly what we're doing as well.

**Comment by odrobnik** [comment]
@finestructure Now the next riddle...

Your [FAQ](https://swiftpackageindex.com/docs/builds#built-how) states: 

> When running xcodebuild, we apply some heuristics to find the correct scheme to build. If a package contains a single scheme (as reported by xcodebuild -list), the build system will use that scheme.

But contrary to that I see that first the name of the package seems to be tried, even though there are multiple shared schemes contained in the xcodeproj

**Comment by finestructure** [comment]
The complete logic is as follows:

```swift
func findScheme(at path: String, platform: Platform, swiftVersion: SwiftVersion) throws -> String {
    if let scheme = SPIManifest.load(in: path).flatMap({ $0.scheme(for: platform) }) {
        return scheme
    }

    let schemes = (try? xcodebuildList(at: path, swiftVersion: swiftVersion)) ?? []

    if schemes.count == 1 {
        return schemes.first!
    } else {
        if let packageScheme = schemes.first(where: { $0.hasSuffix("-Package") }) {
            return packageScheme
        }

        // We have multiple schemes but no -Package scheme
        // Remove any xcodeproj or xcworkspace files and list schemes again
        try Current.shell.run(command: .init(string: "rm -rf *.{xcodeproj,xcworkspace}"), at: path)

        let schemes = try xcodebuildList(at: path, swiftVersion: swiftVersion)

        guard !schemes.isEmpty else { throw Error.noSchemes }

        if schemes.count == 1 { return schemes.first! }

        guard let packageScheme = schemes.first(where: { $0.hasSuffix("-Package") })
        else {
            print("Schemes found:")
            schemes.forEach { print("  \($0)") }
            throw Error.noPackageScheme
        }
        return packageScheme
    }
}
```

What does `xcodebuild -list` show for your project? And which scheme is shown when you run the build command that's listed on the build details page?

**Comment by finestructure** [comment]
NB: `<packageName>-Package` is the naming scheme for the scheme that SPM autogenerates when there's no project file. That's why we're looking for that one.

**Comment by odrobnik** [comment]
What does the first of do? Does that the SPIManifest also reference a scheme?

**Comment by finestructure** [comment]
That's loading the `.spi.yml` override I mentioned upthread.

**Comment by odrobnik** [comment]
Thanks @finestructure - I now got all (except Linux) green for 5.3. Thanks for your patient explanations!

**Comment by daveverwer** [comment]
I'm glad you managed to get it reflecting the true compatibility status Oliver.

One thing that has struck me during this conversation is that our docs need improving, and making more visible. I've opened #746 to start that process. We knew we needed to document the `.spi.yml` file, but it wasn't written down anywhere.

Also, thanks for the very kind sponsorship! We hadn't even announced that we were accepting sponsorship yet, so your sponsorship is very much appreciated!

**Comment by finestructure** [comment]
Indeed, thanks for your support, Oliver!

**Comment by odrobnik** [comment]
Your work on SPI was the key motivation for me to get started with SwiftPM. I had some contributors attempt adding it to some of my open source projects, but did so only partially successful, in part because before 5.3 there was no resource support. 

The green checkmarks made it feel to me a bit like a game. That's why - if you have to use Swift Tools 5.3 because of resources - I argue for omitting lower versions from the chart because you can never get these to go green, which is a bit frustrating.

About the sponsoring, I just noticed this commit 61cd55be4306f1147b6b976202bc4603074a09c2 and followed the link there. Keep up the good work!

**Comment by daveverwer** [comment]
That's great. One of the things I kinda hoped for with the build system was that it would cause package authors to not just blindly add a Package.swift file, but really genuinely verify that it works. We found several packages with syntax errors in Package.swift files etc.

We didn't intend it as a game, but if it gets more compatibility with packages and platforms then that's a good thing. 👍
