### ISSUE TITLE
Build Error: Cannot open "****.docc" as a "Folder" because it is already open as a "Swift User Managed Package Folder"

### ISSUE THREAD

**Issue by MaximBazarov** [SwiftPackageIndex/SwiftPackageIndex-Server#2073]
Build error while building the package for `tvOS` target.

[7C376C8A-482A-4EEF-8EE0-2C4532B2F54A](https://swiftpackageindex.com/builds/7C376C8A-482A-4EEF-8EE0-2C4532B2F54A)

**The steps needed to reproduce the bug**

1. Release a package or trigger package build
3. See an error in build log

**Expected behaviour**
Package builds

**Actual behaviour**
```
Failed to load container at path: /Users/builder/builds/ogLoW6xX/1/finestructure/swiftpackageindex-builder/spi-builder-workspace/Sources/Inject.docc, 
Error: 
    Error Domain=com.apple.dt.IDEContainerErrorDomain 
    Code=6 
    "Cannot open "Inject.docc" as a "Folder" because it is already open as a "Swift User Managed Package Folder"." 
    UserInfo={
        NSLocalizedDescription=Cannot open "Inject.docc" as a "Folder" because it is already open as a "Swift User Managed Package Folder".
    }
{
  "workspace" : {
    "name" : "spi-builder-workspace",
    "schemes" : [
      "Inject"
    ]
  }
}
Running build ...
env DEVELOPER_DIR="/Applications/Xcode-14.0.0-Beta.6.app" xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -derivedDataPath "$PWD/.derivedData" build -scheme "Inject" -destination "generic/platform=tvos"
Command line invocation:
    /Applications/Xcode-14.0.0-Beta.6.app/Contents/Developer/usr/bin/xcodebuild -IDEClonedSourcePackagesDirPathOverride=/Users/builder/builds/ogLoW6xX/1/finestructure/swiftpackageindex-builder/spi-builder-workspace/.dependencies -derivedDataPath /Users/builder/builds/ogLoW6xX/1/finestructure/swiftpackageindex-builder/spi-builder-workspace/.derivedData build -scheme Inject -destination generic/platform=tvos

```

**Additional context**

It successfully builds on other platforms, and doesn't use any APIs that might be tvOS specific.

**Comment by finestructure** [comment]
I can't test this with 14.0.0-Beta.6 locally because I hadn't downloaded the tvOS SDK at the time it came out and it's not available anymore it seems.

However, 14.1b3 seems to reproduce the issue the same.

I believe the `already open` error message is a red herring. Building the 1.0.0 release shows that the issue seems to be the `. tvOS(.v11)` directive:

```
/Users/sas/Projects/SPI/spi-builder/checkout/Tests/Utility/Samples.swift:35:7: error: concurrency is only available in tvOS 13.0.0 or newer
actor Auth: AuthInterface {
      ^
```

If I change this to `.v13` the build works locally.

I see `main` has this set to `v15` but I suspect our build isn't tracking the latest `main` yet.

**Comment by finestructure** [comment]
Actually, it seems you downgraded to `v11` [here](https://github.com/MaximBazarov/Inject/commit/879518659aa3ae3fb4804e1b964b375e58ef5bee), so I think this failure is correct?

**Comment by finestructure** [comment]
I think your latest change should then make this pass again: https://github.com/MaximBazarov/Inject/commit/baba240a06f9e33337eb64639756c2f50d964c82

**Comment by MaximBazarov** [comment]
> Actually, it seems you downgraded to `v11` [here](https://github.com/MaximBazarov/Inject/commit/879518659aa3ae3fb4804e1b964b375e58ef5bee), so I think this failure is correct?

yes that what I suspected, thank you, we will see in the next version I'm planning to release tomorrow

**Comment by MaximBazarov** [comment]
ok, It worked on `1.0.1`, but failed on `main` branch with same error, I think something there is flaky cuz they both point to the same commit

**Comment by finestructure** [comment]
I don’t think the main branch has processed yet. We coalesce default branch builds by up to 24h.

**Comment by finestructure** [comment]
Yes, that build is for 879518659aa3ae3fb4804e1b964b375e58ef5bee

**Comment by MaximBazarov** [comment]
Ok, I see, I think we can close the issue then, error seems to be a race condition to the folder access tho, but doesn't seem like a big issue now imo

**Comment by finestructure** [comment]
It's caught up now!

<img width="734" alt="CleanShot 2022-10-14 at 11 05 39@2x" src="https://user-images.githubusercontent.com/65520/195808325-3dea84f8-78c5-4919-b1ac-029a0863e527.png">
